site_name: BehaviorTree.CPP
site_description: Introduction to Behavior Trees
site_author: Davide Faconti

copyright: 'Copyright &copy; 2018 Davide Faconti, Eurecat'

theme:
  name: 'material'
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  
repo_name: 'Eurecat/BehaviorTree.CPP'
repo_url: 'https://github.com/Eurecat/BehaviorTree.CPP'

markdown_extensions:
  - admonition


pages:
    - Home: index.md
    - Introduction BTs: 02_BT_description.md
